### PR TITLE
feat(backend): Setup architecture

### PR DESCRIPTION
**Pull request by Sanix-Darker**
#### This pull request does...

**Why ?**
Because we need a good structure of the backend before going further

**How ?**
A complete re-organisation per module with routes, handler and models affiliated to them, like this :
```shell
.
├── app
│   ├── auth
│   │   ├── handlers.go
│   │   ├── models.go
│   │   └── routers.go
│   ├── organisation
│   │   ├── handlers.go
│   │   ├── models.go
│   │   └── routers.go
│   ├── settings.go
│   └── utils.go
├── db
│   └── db.go
├── go.mod
├── go.sum
├── main.go
├── Makefile
└── migrations
    └── 001_initial.sql
```

**Steps to verify:**
N/A

** Screenshots (optional)
N/A

### CODE REVIEW

**Comment by DipandaAser** [comment]
@Sanix-Darker you need to add at least one line in backend/app/utils.go, the package declaration 
`package app` this is why Check / build (pull_request) fail

**Comment by DipandaAser** [comment]
Sound good to me after a discussion with @Sanix-Darker

**Review by DipandaAser — APPROVED** [review]

**Review by bw-bmbarga — COMMENTED** [review]
It seems that this PR is adding some scaffold for building future endpoints. Don't you think it is simpler to implement one endpoint at a time instead of having multiple endpoints that we might forget to implement or have to change later if we are not happy with the architecture ?

**Comment by DipandaAser** [comment]
@bw-bmbarga we just want to have one registering func for different handlers of a module instead of registering all those handlers in one place.

**Pull request merged**
